apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: etcd
    etcd_cluster: sensu-etcd
    release: prometheus
  name: etcd
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - path: /metrics
    port: client
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
      etcd_cluster: sensu-etcd

