apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    etcd_cluster: sensu-etcd
    svcmon: sensu-etcd
  name: sensu-etcd-monitoring
  namespace: monitoring
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
    etcd_cluster: sensu-etcd
  type: ClusterIP
