apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensu
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "sensu.{{ .Values.ingress.dns-zone }},sensu-api.{{ .Values.ingress.dns-zone }},sensu-agent-api.{{ .Values.ingress.dns-zone }}"
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  - secretName: sensu-tls
    hosts:
    - sensu.{{ .Values.ingress.dns-zone }}
    - sensu-api.{{ .Values.ingress.dns-zone }}
    - sensu-agent-api.{{ .Values.ingress.dns-zone }}
  rules:
    - host: sensu.{{ .Values.ingress.dns-zone }}
      http:
        paths:
          - backend:
              serviceName: sensu
              servicePort: dashboard
    - host: sensu-api.{{ .Values.ingress.dns-zone }}
      http:
        paths:
          - backend:
              serviceName: sensu
              servicePort: sensu-api
    - host: sensu-agent-api.{{ .Values.ingress.dns-zone }}
      http:
        paths:
          - backend:
              serviceName: sensu
              servicePort: agent-api