apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensu
  namespace: {{ .Values.namespace }}
spec:
  serviceName: sensu
  # replicas: 3
  selector:
    matchLabels:
      app: sensu
  template:
    metadata:
      labels:
        app: sensu
    spec:
      containers:
      - name: sensu
        image: sensu/sensu:5.2.0
        command:
        - sensu-backend
        - start
        - --no-embed-etcd
        - --etcd-advertise-client-urls=http://sensu-etcd-client.{{ .Values.namespace }}.svc.cluster.local:2379
        ports:
        - containerPort: 2380
          name: bk-intercon
        - containerPort: 3000
          name: dashboard
        - containerPort: 8080
          name: sensu-api
        - containerPort: 8081
          name: agent-api
        resources:
          limits:
            cpu: 15m
            memory: 60Mi
          requests:
            cpu: 5m
            memory: 15Mi
  #       volumeMounts:
  #       - name: state
  #         mountPath: /var/lib/sensu
  # volumeClaimTemplates:
  # - metadata:
  #     name: state
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 10Gi