apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensu
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:001579709704:certificate/b5b154bb-0ee7-4d94-a7cd-da8bb456d506
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
spec:
  rules:
    - host: sensu.dev.aws.csservice.de
      http:
        paths:
          - backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - backend:
              serviceName: sensu
              servicePort: dashboard
    - host: sensu-api.dev.aws.csservice.de
      http:
        paths:
          - backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
          - backend:
              serviceName: sensu
              servicePort: sensu-api
    - host: sensu-agent-api.dev.aws.csservice.de
      http:
        paths:
          - backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - backend:
              serviceName: sensu
              servicePort: agent-api